### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by liamxg** [hzi-bifo/CoronaDataVis#1]
when i run the code "case_seq_df <- create_case_seq_df(seq_country_date, case_country_date, country_list) %>% 
  filter(week >= "2020-W08")"

then reported that: `summarise()` has grouped output by 'country'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'country'. You can override using the `.groups` argument.
 Error in na.locf(.) : could not find function "na.locf" 

could you please help me out, thanks.

**Comment by dawnmy** [comment]
Sorry for the late reply. I just noticed your message. You probably need to install library `zoo` and load it before your run the script.

**Comment by liamxg** [comment]
thanks for your help, could I know your email, please.

**Comment by dawnmy** [comment]
dawnmsg#gmail.com

**Comment by liamxg** [comment]
@dawnmy, thanks. I have sent the email to you.

**Comment by dawnmy** [comment]
> @dawnmy, thanks. I have sent the email to you.

Sorry, I did not receive your email. Did you replace # with @?

**Comment by liamxg** [comment]
yes, I emailed you two times, without reply.

**Comment by dawnmy** [comment]
> yes, I emailed you two times, without reply.

replied you. I will close this issue. Feel free to reopen it if you have any further questions.
